Fix missing include file.
src/hotspot/share/runtime/threads.cpp: In static member function 'static jint Threads::check_for_restore(JavaVMInitArgs*)':
src/hotspot/share/runtime/threads.cpp:415:5: error: 'crac' has not been declared
  415 |     crac::restore();
      |     ^~~~
src/hotspot/share/runtime/threads.cpp: In static member function 'static jint Threads::create_vm(JavaVMInitArgs*, bool*)':
src/hotspot/share/runtime/threads.cpp:494:3: error: 'crac' has not been declared
  494 |   crac::vm_create_start();
      |   ^~~~