Fix compilation errors:
commit 5d2fe3461534d56b0408788c8d7c1b94f85530c0
../../src/hotspot/share/runtime/arguments.cpp: In static member function 'static jint Arguments::finalize_vm_init_args(bool)':
../../src/hotspot/share/runtime/arguments.cpp:3235:28: error: 'crac' has not been declared
 3235 |   if (CRaCCheckpointTo && !crac::prepare_checkpoint()) {
      |                            ^~~~

../../src/hotspot/share/prims/jvm.cpp: In function '_jobjectArray* JVM_Checkpoint(JNIEnv*, jarray, jobjectArray, jboolean, jlong)':
../../src/hotspot/share/prims/jvm.cpp:3853:16: error: 'crac' has not been declared
 3853 |   Handle ret = crac::checkpoint(fd_arr, obj_arr, dry_run, jcmd_stream, CHECK_NULL);
      |                ^~~~
../../src/hotspot/share/services/management.cpp: In function 'jlong get_long_attribute(jmmLongAttribute)':
../../src/hotspot/share/services/management.cpp:957:12: error: 'crac' has not been declared
  957 |     return crac::restore_start_time();
      |            ^~~~
../../src/hotspot/share/services/management.cpp:961:21: error: 'crac' has not been declared
  961 |       jlong ticks = crac::uptime_since_restore();
      |                     ^~~~

Remove a no longer used declaration of os::Linux::checkpoint_restore().